#include <stddef.h>
#include <stdint.h>

#include "lvgl.h"

// Generated by scripts/convert-revenant-grid-v2.sh and embedded by ESP-IDF.
// LVGL reads these fixed-size RGB565 pixels directly with no PNG decode.
extern const uint8_t revenant_grid_v2_rgb565_start[]
    asm("_binary_revenant_grid_v2_rgb565_start");

const lv_image_dsc_t revenant_grid_v2_background = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565,
        .flags = 0,
        .w = 410,
        .h = 502,
        .stride = 820,
        .reserved_2 = 0,
    },
    .data_size = 410U * 502U * 2U,
    .data = revenant_grid_v2_rgb565_start,
    .reserved = NULL,
};
