#pragma once

// Host-only verifier fixture. Production configuration is generated by
// ESP-IDF and remains empty/fail-closed until an approved public key exists.
#define CONFIG_NIGHTGLASS_OTA_P256_PUBLIC_KEY_HEX ""
